name: Release

on:
  workflow_call:

permissions:
  contents: write # needed to write releases
  packages: write # needed for ghcr access

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Force checking out a full tree, so we get tags and previous commits
          # This is necessary for svu and git-cliff to work properly
          fetch-depth: 0
      - name: Setup SVU
        id: svu
        uses: obfu5c8/action-svu@v1.0.0
        with:
          svu-version: 1.12.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3 # login to ghcr
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/richiesams/certbot_cron:${{ steps.svu.outputs.version }}
      - name: Generate changelog
        id: git-cliff
        uses: orhun/git-cliff-action@v3.0.2
        with:
          args: --latest --strip all
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.svu.outputs.version }}
          name: Release ${{ steps.svu.outputs.version }}
          body: ${{ steps.git-cliff.outputs.content }}
